# Generated by Django 6.0.3 on 2026-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this leave type is available for new applications'),
        ),
    ]
