# Generated by Django 6.0.3 on 2026-03-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_employee_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extra_unpaid_days',
            field=models.IntegerField(default=0, help_text='Additional unpaid leave days granted to the employee'),
        ),
    ]
